# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 554b13752aa8aa7e994d513c2bb627f393786d39c3939251d5b92dd67b4c9060e9d85689e422cb748b6be75e73ece8dfc098495ab6eb500bbdacba37d46d87d7

test:
  secret_key_base: cf52d1964617fe4bb1da27b2981c4406a73f809ea2347f04061dec288bd36ad0e94cbdd6a32c3ce4ac5c7c85b6bbed657a596c2239f8bc7b4e0ab0d3032d12aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
